// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh_1V7oNxvlABN-4u9ygX0jjz3CwWMO7M',
    appId: '1:640627704954:web:2781eb34e2176159d867c3',
    messagingSenderId: '640627704954',
    projectId: 'pa-test-da05d',
    authDomain: 'pa-test-da05d.firebaseapp.com',
    databaseURL: 'https://pa-test-da05d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pa-test-da05d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz3GkwEintS4ELioTioXXzqS2A2tF0-UY',
    appId: '1:640627704954:android:805b4c0d6b66c099d867c3',
    messagingSenderId: '640627704954',
    projectId: 'pa-test-da05d',
    databaseURL: 'https://pa-test-da05d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pa-test-da05d.firebasestorage.app',
  );

}